"""
IdeaGPT — Export & Report Compiler Service (Feature 18).
Generates formatted JSON, Markdown, and Institutional Printable PDF reports
with evidence citations, SWOT analysis, decision gates, and sanitized HTML.
"""

import json
from typing import Dict, Any, Optional
import html


class ExportService:
    @staticmethod
    def to_json(result_payload: dict) -> str:
        return json.dumps(result_payload, indent=2)

    @staticmethod
    def to_markdown(result_payload: dict) -> str:
        summary = result_payload.get("summary", "No summary provided.")
        score = result_payload.get("score", 75)
        gate = result_payload.get("decision_gate", "VALIDATE_FIRST")
        strengths = "\n".join(f"- {s}" for s in result_payload.get("strengths", []))
        weaknesses = "\n".join(f"- {w}" for w in result_payload.get("weaknesses", []))
        recs = "\n".join(f"- {r}" for r in result_payload.get("recommendations", []))
        arch = result_payload.get("architecture_breakdown", "Modular monolith with relational PostgreSQL storage.")

        citations = result_payload.get("citations", [])
        cite_str = "\n".join(f"- [{c.get('source_title', 'Source')}]({c.get('source_url', '#')}) ({c.get('domain_trust_level', 'INDUSTRY')})" for c in citations) if citations else "No external citations recorded."

        return f"""# IdeaGPT Strategic Evaluation Report
**Overall Score**: {score}/100  
**Decision Gate**: `{gate}`

---

## Executive Summary
{summary}

## Key Strengths
{strengths}

## Potential Weaknesses & Risks
{weaknesses}

## Strategic Recommendations
{recs}

## Verified Evidence & Citations
{cite_str}

## Technical Feasibility & Architecture
{arch}

---
*Generated by IdeaGPT Institutional Intelligence Engine.*
"""

    @staticmethod
    def to_pdf_html(result_payload: dict, project_title: str = "Startup Venture") -> str:
        """
        Compiles an institutional printable PDF HTML document with styling,
        score badges, citation links, and print pagination.
        """
        score = result_payload.get("score", 75)
        gate = result_payload.get("decision_gate", "VALIDATE_FIRST")
        summary = html.escape(str(result_payload.get("summary", "Executive evaluation summary.")))
        
        strengths_html = "".join(f"<li>{html.escape(str(s))}</li>" for s in result_payload.get("strengths", []))
        weaknesses_html = "".join(f"<li>{html.escape(str(w))}</li>" for w in result_payload.get("weaknesses", []))
        recs_html = "".join(f"<li>{html.escape(str(r))}</li>" for r in result_payload.get("recommendations", []))

        citations = result_payload.get("citations", [])
        cite_html = "".join(
            f"<li><a href='{html.escape(c.get('source_url', '#'))}' target='_blank'><strong>{html.escape(c.get('source_title', 'Source'))}</strong></a> - <span class='badge'>{html.escape(c.get('domain_trust_level', 'INDUSTRY'))}</span></li>"
            for c in citations
        ) if citations else "<li>No external web citations bound.</li>"

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>IdeaGPT Executive Report — {html.escape(project_title)}</title>
    <style>
        @page {{ margin: 20mm; size: A4; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.5; color: #1e293b; background: #fff; max-width: 800px; margin: 0 auto; padding: 20px; }}
        .header {{ border-bottom: 2px solid #4f46e5; padding-bottom: 15px; margin-bottom: 25px; display: flex; justify-content: space-between; align-items: center; }}
        .title {{ font-size: 24px; font-weight: 800; color: #0f172a; margin: 0; }}
        .badge {{ background: #e0e7ff; color: #4338ca; padding: 4px 8px; border-radius: 4px; font-size: 11px; font-weight: 700; text-transform: uppercase; }}
        .gate-badge {{ background: #dbeafe; color: #1e40af; border: 1px solid #93c5fd; padding: 6px 12px; border-radius: 6px; font-size: 13px; font-weight: 800; }}
        .score-box {{ background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 15px; margin-bottom: 20px; display: flex; gap: 20px; }}
        .score-val {{ font-size: 32px; font-weight: 900; color: #4f46e5; }}
        h2 {{ font-size: 16px; font-weight: 700; color: #0f172a; border-bottom: 1px solid #e2e8f0; padding-bottom: 5px; margin-top: 25px; }}
        ul {{ padding-left: 20px; font-size: 13px; color: #334155; }}
        li {{ margin-bottom: 6px; }}
        .footer {{ margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 10px; font-size: 11px; color: #94a3b8; text-align: center; }}
    </style>
</head>
<body>
    <div class="header">
        <div>
            <div class="badge">IdeaGPT Institutional Evaluation</div>
            <h1 class="title">{html.escape(project_title)}</h1>
        </div>
        <div class="gate-badge">GATE: {html.escape(gate)}</div>
    </div>

    <div class="score-box">
        <div>
            <div style="font-size: 11px; color: #64748b; font-weight: 700; text-transform: uppercase;">Overall Score</div>
            <div class="score-val">{score}<span style="font-size: 16px; font-weight: 400; color: #94a3b8;">/100</span></div>
        </div>
        <div style="flex: 1; font-size: 12px; color: #475569; padding-left: 15px; border-left: 1px solid #e2e8f0;">
            <strong>Decision Summary:</strong><br/>
            {summary}
        </div>
    </div>

    <h2>Key Strengths</h2>
    <ul>{strengths_html}</ul>

    <h2>Potential Weaknesses & Execution Risks</h2>
    <ul>{weaknesses_html}</ul>

    <h2>Strategic Recommendations</h2>
    <ul>{recs_html}</ul>

    <h2>Verified Research Sources & Citations</h2>
    <ul>{cite_html}</ul>

    <div class="footer">
        Generated by IdeaGPT Platform • Multi-Provider Universal Gateway & Decision Science Engine
    </div>
</body>
</html>"""


export_service = ExportService()
