"""add_ai_tasks_table

Revision ID: 470ae65e8c8e
Revises: 69a84c00dd55
Create Date: 2026-08-13 16:10:11.655398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '470ae65e8c8e'
down_revision: Union[str, Sequence[str], None] = '69a84c00dd55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('idea_id', sa.String(length=36), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_tasks_idempotency', 'ai_tasks', ['user_id', 'idempotency_key'], unique=False)
    op.create_index('idx_ai_tasks_user_status', 'ai_tasks', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_ai_tasks_idempotency_key'), 'ai_tasks', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_ai_tasks_status'), 'ai_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_ai_tasks_user_id'), 'ai_tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_tasks_user_id'), table_name='ai_tasks')
    op.drop_index(op.f('ix_ai_tasks_status'), table_name='ai_tasks')
    op.drop_index(op.f('ix_ai_tasks_idempotency_key'), table_name='ai_tasks')
    op.drop_index('idx_ai_tasks_user_status', table_name='ai_tasks')
    op.drop_index('idx_ai_tasks_idempotency', table_name='ai_tasks')
    op.drop_table('ai_tasks')
    # ### end Alembic commands ###
