import json
import time
from typing import Any, Dict, List, Optional
from app.ai.providers.base import AIProvider
from app.core.config import settings

class MockProvider(AIProvider):
    def __init__(self):
        self.provider_id = "mock"
        self.display_name = "Mock Provider (Test Mode Only)"

    def list_models(self) -> List[Dict[str, Any]]:
        # MockProvider is ONLY available during tests or when explicitly set as DEFAULT_PROVIDER in dev
        is_test_mode = settings.APP_ENV == "test" or settings.DEFAULT_PROVIDER == "mock"
        return [
            {
                "id": "mock-deterministic-v1",
                "name": "Deterministic Test Model",
                "provider": self.provider_id,
                "capabilities": ["TEXT_GENERATION", "STRUCTURED_OUTPUT"],
                "configured": is_test_mode,
                "available": is_test_mode,
            }
        ]

    async def health(self) -> Dict[str, Any]:
        is_test_mode = settings.APP_ENV == "test" or settings.DEFAULT_PROVIDER == "mock"
        if not is_test_mode:
            return {"available": False, "latency_ms": 0, "error": "MockProvider is disabled in production"}
        return {"available": True, "latency_ms": 1, "error": None}

    async def generate(
        self,
        prompt: str,
        system_prompt: str = "",
        response_format: str = "json",
        model_override: Optional[str] = None
    ) -> Dict[str, Any]:
        mock_response = {
            "score": 85,
            "summary": "Automated evaluation generated by test model.",
            "strengths": [
                "Strong user demand with high validation need.",
                "SaaS monetization potential.",
                "Robust modern technology recommendations."
            ],
            "weaknesses": [
                "Competition with low-barrier developer wrappers.",
                "Privacy leakage risks from direct client browser integration."
            ],
            "market_analysis": "The automation and AI tooling space is growing aggressively with a dynamic CAGR projection of over 20%.",
            "recommendations": [
                "Introduce localized rate limiting on client-facing API proxies.",
                "Integrate a failover orchestration router."
            ],
            "confidence": 0.9,
            "dimensions": {
                "innovation": 85,
                "market_potential": 80,
                "technical_feasibility": 90,
                "business_viability": 85,
                "scalability": 85,
                "execution_complexity": 70,
                "competitive_differentiation": 80
            },
            "architecture_breakdown": "### Test Evaluation Blueprint\n\n- **Frontend**: Next.js 14+ with local React state\n- **Backend**: FastAPI with async route dependencies\n- **Database**: PostgreSQL 18.x with SQLAlchemy async."
        }
        if response_format == "json":
            return mock_response
        return {"text": json.dumps(mock_response)}
